version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deep-thoughts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1itxj6pd0vlmr"
s3_prefix = "deep-thoughts"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
